"""Central catalog — all supported providers declared here.

Adding a new provider = add one Provider(...) entry and optionally
models in api.providers.models. No other code changes required.

Accuracy note (2026-01 cutoff): endpoints and auth methods verified
against official docs. Model IDs are representative verified samples;
rapidly-changing catalogs are marked dynamic and discovered via API
where possible rather than hard-coded exhaustively.
"""

from .registry import Provider, register_provider

# fmt: off

PROVIDERS: list[Provider] = [
    Provider(
        id="openai",
        name="OpenAI",
        env_var="OPENAI_API_KEY",
        base_url="https://api.openai.com/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://platform.openai.com/docs/api-reference",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.openai.com/v1/models",
        validation_method="GET",
        models_endpoint="/models",
        supports_model_discovery=True,
        description="OpenAI GPT, reasoning, embedding and audio models",
    ),
    Provider(
        id="anthropic",
        name="Anthropic",
        env_var="ANTHROPIC_API_KEY",
        base_url="https://api.anthropic.com",
        auth_method="x-api-key",
        auth_header="x-api-key",
        doc_url="https://docs.anthropic.com/en/api",
        openai_compatible=False,
        supports_streaming=True,
        validation_endpoint="https://api.anthropic.com/v1/models",
        validation_method="GET",
        models_endpoint="/v1/models",
        supports_model_discovery=True,
        extra_env_vars=["ANTHROPIC_AUTH_TOKEN"],
        description="Claude Opus / Sonnet / Haiku",
    ),
    Provider(
        id="google",
        name="Google Gemini",
        env_var="GOOGLE_API_KEY",
        base_url="https://generativelanguage.googleapis.com",
        auth_method="query_param",
        auth_header="query:key",
        doc_url="https://ai.google.dev/gemini-api/docs",
        openai_compatible=False,
        supports_streaming=True,
        validation_endpoint="https://generativelanguage.googleapis.com/v1/models",
        validation_method="GET",
        models_endpoint="/v1/models",
        supports_model_discovery=True,
        extra_env_vars=["GEMINI_API_KEY", "GOOGLE_GENAI_API_KEY"],
        aliases=["gemini", "googlegemini"],
        description="Gemini Flash / Pro via Generative Language API",
    ),
    Provider(
        id="xai",
        name="xAI",
        env_var="XAI_API_KEY",
        base_url="https://api.x.ai/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://docs.x.ai/api",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.x.ai/v1/models",
        models_endpoint="/models",
        supports_model_discovery=True,
        extra_env_vars=["GROK_API_KEY"],
        description="Grok models",
    ),
    Provider(
        id="deepseek",
        name="DeepSeek",
        env_var="DEEPSEEK_API_KEY",
        base_url="https://api.deepseek.com",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://api-docs.deepseek.com/",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.deepseek.com/v1/models",
        models_endpoint="/v1/models",
        supports_model_discovery=True,
        description="DeepSeek chat and reasoner",
    ),
    Provider(
        id="mistral",
        name="Mistral AI",
        env_var="MISTRAL_API_KEY",
        base_url="https://api.mistral.ai/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://docs.mistral.ai/api/",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.mistral.ai/v1/models",
        models_endpoint="/models",
        supports_model_discovery=True,
        description="Mistral Large/Small, Codestral, Ministral",
    ),
    Provider(
        id="groq",
        name="Groq",
        env_var="GROQ_API_KEY",
        base_url="https://api.groq.com/openai/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://console.groq.com/docs/api-reference",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.groq.com/openai/v1/models",
        models_endpoint="/models",
        supports_model_discovery=True,
        description="Groq inference - Llama, Mixtral, Gemma",
    ),
    Provider(
        id="together",
        name="Together AI",
        env_var="TOGETHER_API_KEY",
        base_url="https://api.together.xyz/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://docs.together.ai/reference",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.together.xyz/v1/models",
        models_endpoint="/models",
        supports_model_discovery=True,
        description="Together inference - Llama, Qwen, DeepSeek, etc.",
    ),
    Provider(
        id="openrouter",
        name="OpenRouter",
        env_var="OPENROUTER_API_KEY",
        base_url="https://openrouter.ai/api/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://openrouter.ai/docs/api-reference/overview",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://openrouter.ai/api/v1/auth/key",
        models_endpoint="/models",
        supports_model_discovery=True,
        description="OpenRouter - unified gateway to 200+ models (dynamic catalog)",
    ),
    Provider(
        id="fireworks",
        name="Fireworks AI",
        env_var="FIREWORKS_API_KEY",
        base_url="https://api.fireworks.ai/inference/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://docs.fireworks.ai/api-reference",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.fireworks.ai/inference/v1/models",
        models_endpoint="/models",
        supports_model_discovery=True,
        extra_env_vars=["FIREWORKS_API_TOKEN"],
        description="Fireworks inference",
    ),
    Provider(
        id="perplexity",
        name="Perplexity",
        env_var="PERPLEXITY_API_KEY",
        base_url="https://api.perplexity.ai",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://docs.perplexity.ai/api-reference/chat-completions",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.perplexity.ai/chat/completions",
        models_endpoint=None,
        supports_model_discovery=False,
        extra_env_vars=["PPLX_API_KEY"],
        description="Perplexity Sonar models",
    ),
    Provider(
        id="cerebras",
        name="Cerebras",
        env_var="CEREBRAS_API_KEY",
        base_url="https://api.cerebras.ai/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://inference-docs.cerebras.ai/api-reference",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.cerebras.ai/v1/models",
        models_endpoint="/models",
        supports_model_discovery=True,
        description="Cerebras inference",
    ),
    Provider(
        id="cohere",
        name="Cohere",
        env_var="COHERE_API_KEY",
        base_url="https://api.cohere.ai/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://docs.cohere.com/reference/chat",
        openai_compatible=False,
        supports_streaming=True,
        validation_endpoint="https://api.cohere.com/v1/models",
        models_endpoint="/models",
        supports_model_discovery=True,
        description="Cohere Command, Embed, Rerank",
    ),
    Provider(
        id="ai21",
        name="AI21 Labs",
        env_var="AI21_API_KEY",
        base_url="https://api.ai21.com/studio/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://docs.ai21.com/reference",
        openai_compatible=False,
        supports_streaming=False,
        validation_endpoint="https://api.ai21.com/studio/v1/models",
        supports_model_discovery=False,
        description="AI21 Jamba models",
    ),
    Provider(
        id="sambanova",
        name="SambaNova",
        env_var="SAMBANOVA_API_KEY",
        base_url="https://api.sambanova.ai/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://docs.sambanova.ai/",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.sambanova.ai/v1/models",
        models_endpoint="/models",
        supports_model_discovery=True,
        description="SambaNova Cloud inference",
    ),
    Provider(
        id="deepinfra",
        name="DeepInfra",
        env_var="DEEPINFRA_API_KEY",
        base_url="https://api.deepinfra.com/v1/openai",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://deepinfra.com/docs/openai_api",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.deepinfra.com/v1/openai/models",
        models_endpoint="https://api.deepinfra.com/v1/openai/models",
        supports_model_discovery=True,
        extra_env_vars=["DEEPINFRA_TOKEN"],
        description="DeepInfra OpenAI-compatible inference",
    ),
    Provider(
        id="replicate",
        name="Replicate",
        env_var="REPLICATE_API_TOKEN",
        base_url="https://api.replicate.com/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://replicate.com/docs/reference/http",
        openai_compatible=False,
        supports_streaming=False,
        validation_endpoint="https://api.replicate.com/v1/account",
        models_endpoint=None,
        supports_model_discovery=False,
        description="Replicate - model catalog is dynamic per-owner; no static list",
    ),
    Provider(
        id="huggingface",
        name="Hugging Face",
        env_var="HF_TOKEN",
        base_url="https://api-inference.huggingface.co",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://huggingface.co/docs/api-inference",
        openai_compatible=False,
        supports_streaming=False,
        validation_endpoint="https://huggingface.co/api/whoami-v2",
        models_endpoint=None,
        supports_model_discovery=False,
        extra_env_vars=["HUGGINGFACE_TOKEN", "HF_API_TOKEN"],
        aliases=["hf"],
        description="Hugging Face Inference API (dynamic model hub)",
    ),
    Provider(
        id="mistral_codestral",
        name="Mistral Codestral",
        env_var="MISTRAL_API_KEY",
        base_url="https://api.mistral.ai/v1",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://docs.mistral.ai/api/",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint="https://api.mistral.ai/v1/models",
        status="active",
        description="Alias for codestral via Mistral API",
    ),
    # Cloud / special-auth providers — marked special_auth, no naive key validation
    Provider(
        id="bedrock",
        name="Amazon Bedrock",
        env_var="AWS_BEARER_TOKEN_BEDROCK",
        base_url="https://bedrock-runtime.{region}.amazonaws.com",
        auth_method="aws_sigv4",
        auth_header="Authorization",
        doc_url="https://docs.aws.amazon.com/bedrock/latest/APIReference/welcome.html",
        openai_compatible=False,
        supports_streaming=True,
        validation_endpoint=None,
        status="special_auth",
        extra_env_vars=["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"],
        description="Bedrock requires AWS SigV4 credentials, not a single API key — use AWS SDK. Marked special_auth.",
    ),
    Provider(
        id="azure_openai",
        name="Azure OpenAI",
        env_var="AZURE_OPENAI_API_KEY",
        base_url="https://{resource}.openai.azure.com/openai",
        auth_method="api_key_header",
        auth_header="api-key",
        doc_url="https://learn.microsoft.com/en-us/azure/ai-services/openai/reference",
        openai_compatible=True,
        supports_streaming=True,
        validation_endpoint=None,
        status="special_auth",
        extra_env_vars=["AZURE_OPENAI_ENDPOINT", "AZURE_API_KEY"],
        description="Azure OpenAI requires endpoint + api-key header. Configure AZURE_OPENAI_ENDPOINT and AZURE_OPENAI_API_KEY.",
    ),
    Provider(
        id="vertex",
        name="Google Vertex AI",
        env_var="GOOGLE_APPLICATION_CREDENTIALS",
        base_url="https://{location}-aiplatform.googleapis.com/v1",
        auth_method="gcp_oauth",
        auth_header="Authorization",
        doc_url="https://cloud.google.com/vertex-ai/docs/reference/rest",
        openai_compatible=False,
        supports_streaming=True,
        validation_endpoint=None,
        status="special_auth",
        extra_env_vars=["GOOGLE_CLOUD_PROJECT", "VERTEX_API_KEY"],
        description="Vertex AI uses GCP service-account OAuth, not a simple API key. Use gcloud auth.",
    ),
    # Non-AI services already scanned (kept for backward compat, mapped as providers too)
    Provider(
        id="stripe",
        name="Stripe",
        env_var="STRIPE_API_KEY",
        base_url="https://api.stripe.com",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://docs.stripe.com/api",
        openai_compatible=False,
        supports_streaming=False,
        validation_endpoint="https://api.stripe.com/v1/charges?limit=1",
        description="Stripe payments API",
    ),
    Provider(
        id="github",
        name="GitHub",
        env_var="GITHUB_TOKEN",
        base_url="https://api.github.com",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://docs.github.com/en/rest",
        supports_streaming=False,
        validation_endpoint="https://api.github.com/user",
        description="GitHub API",
    ),
    Provider(
        id="telegram",
        name="Telegram Bot",
        env_var="TELEGRAM_BOT_TOKEN",
        base_url="https://api.telegram.org",
        auth_method="none",
        auth_header="",
        doc_url="https://core.telegram.org/bots/api",
        supports_streaming=False,
        validation_endpoint="https://api.telegram.org/bot{token}/getMe",
        description="Telegram Bot API",
    ),
    Provider(
        id="slack",
        name="Slack",
        env_var="SLACK_BOT_TOKEN",
        base_url="https://slack.com/api",
        auth_method="bearer",
        auth_header="Authorization",
        doc_url="https://api.slack.com/methods/auth.test",
        supports_streaming=False,
        validation_endpoint="https://slack.com/api/auth.test",
        description="Slack API",
    ),
    # Coding-agent ecosystems — no public key API, mark unsupported rather than fake
    Provider(
        id="opencode",
        name="OpenCode",
        env_var="OPENCODE_API_KEY",
        base_url="",
        auth_method="none",
        auth_header="",
        doc_url="https://opencode.ai",
        openai_compatible=False,
        supports_streaming=False,
        status="unsupported",
        description="OpenCode is a local AI coding agent framework; it has no hosted public API to validate. Use provider APIs it calls (OpenAI, Anthropic, etc.).",
    ),
    Provider(
        id="cursor",
        name="Cursor",
        env_var="CURSOR_API_KEY",
        base_url="",
        auth_method="none",
        auth_header="",
        doc_url="https://docs.cursor.com",
        openai_compatible=False,
        supports_streaming=False,
        status="unsupported",
        description="Cursor does not expose a public API key for programmatic model access. No integration available.",
    ),
    Provider(
        id="kiro",
        name="Kiro",
        env_var="KIRO_API_KEY",
        base_url="",
        auth_method="none",
        auth_header="",
        doc_url="https://kiro.dev",
        openai_compatible=False,
        supports_streaming=False,
        status="unsupported",
        description="Kiro (AWS) does not expose a standalone public model API. Use Bedrock-backed auth instead.",
    ),
]
# fmt: on

for _p in PROVIDERS:
    try:
        register_provider(_p)
    except ValueError:
        # alias duplicate already registered — ignore
        pass
